# Generated by Django 3.0 on 2020-04-01 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extended_user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='extended_user',
            name='country',
        ),
        migrations.AddField(
            model_name='extended_user',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Selected_cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.CharField(max_length=20, null=True)),
                ('hometown', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
