# Generated by Django 3.0 on 2020-03-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200323_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_theme_id', models.CharField(max_length=30)),
                ('image_theme', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
