# Generated by Django 3.0 on 2020-03-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200325_0717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image_Theme',
            new_name='Image_Them',
        ),
    ]
