# Generated by Django 3.0 on 2020-03-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200325_0720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image_Them',
            new_name='Image_Theme',
        ),
    ]
