# Generated by Django 3.0 on 2020-03-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200325_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_theme',
            name='var',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
