# Generated by Django 3.0 on 2020-03-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_image_theme_var'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_theme',
            name='var',
        ),
    ]
