# Generated by Django 3.0 on 2020-03-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_image_theme_var'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_theme',
            name='condition',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
