# Generated by Django 3.0 on 2020-05-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200326_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_theme',
            name='image_theme',
        ),
        migrations.AddField(
            model_name='image_theme',
            name='image_url',
            field=models.CharField(max_length=10000, null=True, unique=True),
        ),
    ]
