# Generated by Django 3.0 on 2020-05-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200508_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_Theme',
        ),
    ]
